### ISSUE TITLE
This data actually belongs to the organisers of FIRE track. 

### ISSUE THREAD

**Issue by amarnamarpan** [baruaranojoy/Catchphrase-extraction-from-legal-documents#1]
Thank you for hosting the data. But please refer the original paper where this dataset was introduced.
Please also give a reference to the FIRE overview paper on [ceur-ws.org](http://ceur-ws.org/) if you are hosting this data.
It is appreciated that you paste the following in the Readme file. 

## Reference
If you use this code in your work, please cite our original paper:
[Automatic Catchphrase Identification from Legal Court Case Documents, by A Mandal, K Ghosh, A Pal, S Ghosh at CIKM, 2017](https://dl.acm.org/doi/10.1145/3132847.3133102)

This data was also used to host a track at FIRE'17.
[Overview of the FIRE 2017 IRLeD Track: Information Retrieval from Legal Documents, by A Mandal,  K Ghosh, A Pal, A Bhattacharya, S Ghosh] (https://www.semanticscholar.org/paper/Overview-of-the-FIRE-2017-IRLeD-Track%3A-Information-Mandal-Ghosh/cb615ed8db3e3245cd8f67a212b40eb42ecce0a7)

**Comment by baruaranojoy** [comment]
I have made required amendments in the readme file, can you please verify and close the issue.

**Comment by amarnamarpan** [comment]
Yes. Thank You.
